title: Kevin Daniel
description: Kevin Daniel | Cybersecurity + AI Entrepreneur
baseurl: ""
url: ""
github_username: kxvinkxvin
image: assets/images/profile.png

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 

favicon: assets/images/favicon.ico