title: Kevin Daniel | Links
description: All the links you need to know for Kevin Daniel. Cybersecurity + AI Entrepreneur, Founder of Breached Labs, OSCE3 Holder
baseurl: ""
url: ""
github_username: kxvinkxvin

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore 

favicon: assets/images/favicon.ico